import { Building2, Car, Eye, HandHeart, Pencil, Stethoscope, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { cx } from '../../../lib/cx'
import { supportCategoryLabels, supportStatusLabels, type SupportCategory, type SupportResource } from '../model/supportTypes'

const categoryClassNames: Record<SupportCategory, string> = { CLINICA: 'bg-[#e2f1ff] text-[#005383]', ONG: 'bg-[#f6eee8] text-[#7a3424]', TRANSPORTE: 'bg-[#eaf4ef] text-[#216346]', PSICOLOGO: 'bg-[#e9effb] text-[#193c67]', CASA_APOIO: 'bg-[#fff0eb] text-[#9c3b29]' }
const categoryIcons: Record<SupportCategory, typeof Building2> = { CLINICA: Building2, ONG: HandHeart, TRANSPORTE: Car, PSICOLOGO: Stethoscope, CASA_APOIO: Building2 }

export function SupportListTable({ resources, page, totalPages, onDelete, onPageChange }: { resources: SupportResource[]; page: number; totalPages: number; onDelete: (resource: SupportResource) => void; onPageChange: (page: number) => void }) {
  return <section className="overflow-hidden rounded-3xl bg-white shadow-[4px_4px_0_rgba(187,202,196,0.2),inset_2px_2px_4px_rgba(215,219,218,0.5)]"><div className="overflow-x-auto"><table className="w-full min-w-[var(--admin-table-min-width)] border-collapse text-left"><thead className="bg-surface-soft text-xs font-bold uppercase tracking-[0.6px] text-muted-strong"><tr><th className="px-4 py-4">Detalhes do local</th><th className="px-4 py-4">Tipo</th><th className="px-4 py-4">Região</th><th className="px-4 py-4">Contatos</th><th className="px-4 py-4">Status</th><th className="w-32 px-4 py-4 text-center">Ações</th></tr></thead><tbody>
    {resources.length === 0 ? <tr><td className="px-4 py-12 text-center text-sm text-muted" colSpan={6}>Nenhum apoio encontrado.</td></tr> : resources.map((resource) => { const Icon = categoryIcons[resource.tipoApoio]; return <tr className="border-t border-[#bbcac4]/15" key={resource.id}><td className="max-w-[var(--admin-table-title-max)] px-4 py-4"><p className="truncate text-base text-admin-text">{resource.nome}</p><p className="truncate text-xs text-muted">{resource.endereco.logradouro}, {resource.endereco.numero} - {resource.endereco.bairro}</p></td><td className="px-4 py-4"><span className={cx('inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-semibold', categoryClassNames[resource.tipoApoio])}><Icon size={12} />{supportCategoryLabels[resource.tipoApoio]}</span></td><td className="px-4 py-4 text-sm text-admin-text">{resource.endereco.cidade}<span className="block text-xs text-muted">{resource.endereco.estado}</span></td><td className="px-4 py-4 text-sm text-muted-strong">{resource.telefone}</td><td className="px-4 py-4"><span className={cx('inline-flex rounded-full px-3 py-1 text-xs font-semibold', resource.status === 'ATIVO' ? 'bg-brand-mint/20 text-brand-teal' : 'bg-[#e6e9e8] text-muted-strong')}>{supportStatusLabels[resource.status]}</span></td><td className="px-4 py-4"><div className="flex justify-center gap-1"><Link aria-label={`Visualizar ${resource.nome}`} className="inline-grid h-8 w-8 place-items-center rounded-full text-muted-strong transition hover:bg-surface-soft focus-visible:outline-2 focus-visible:outline-brand-mint" to={`/radar-de-apoio/${resource.id}/editar`}><Eye size={16} /></Link><Link aria-label={`Editar ${resource.nome}`} className="inline-grid h-8 w-8 place-items-center rounded-full text-muted-strong transition hover:bg-surface-soft focus-visible:outline-2 focus-visible:outline-brand-mint" to={`/radar-de-apoio/${resource.id}/editar`}><Pencil size={16} /></Link><button aria-label={`Desativar ${resource.nome}`} className="inline-grid h-8 w-8 place-items-center rounded-full text-muted-strong transition hover:bg-red-50 hover:text-red-700 focus-visible:outline-2 focus-visible:outline-brand-mint" onClick={() => onDelete(resource)} type="button"><Trash2 size={16} /></button></div></td></tr> })}
  </tbody></table></div><footer className="flex items-center justify-between border-t border-[#bbcac4]/15 bg-surface-soft px-4 py-3"><p className="text-xs text-muted">Página {page} de {totalPages}</p><div className="flex items-center gap-2"><button aria-label="Página anterior" className="rounded px-2 text-muted-strong disabled:opacity-40" disabled={page <= 1} onClick={() => onPageChange(page - 1)} type="button">‹</button><span className="grid h-7 min-w-7 place-items-center rounded-full bg-brand-teal px-2 text-xs text-white">{page}</span><button aria-label="Próxima página" className="rounded px-2 text-muted-strong disabled:opacity-40" disabled={page >= totalPages} onClick={() => onPageChange(page + 1)} type="button">›</button></div></footer></section>
}
