import { Building2, Car, HandHeart, MoreVertical, Pencil, Stethoscope } from 'lucide-react'
import { Link } from 'react-router-dom'
import { cx } from '../../../lib/cx'
import { supportCategoryLabels, supportStatusLabels, type SupportCategory, type SupportResource } from '../model/supportTypes'

const categoryClassNames: Record<SupportCategory, string> = { CLINICA: 'bg-[#e2f1ff] text-[#005383]', ONG: 'bg-[#f6eee8] text-[#7a3424]', TRANSPORTE: 'bg-[#eaf4ef] text-[#216346]', PSICOLOGO: 'bg-[#e9effb] text-[#193c67]', CASA_DE_SUPORTE: 'bg-[#fff0eb] text-[#9c3b29]' }
const categoryIcons: Record<SupportCategory, typeof Building2> = { CLINICA: Building2, ONG: HandHeart, TRANSPORTE: Car, PSICOLOGO: Stethoscope, CASA_DE_SUPORTE: Building2 }

export function SupportListTable({ resources, page, totalPages, onPageChange }: { resources: SupportResource[]; page: number; totalPages: number; onPageChange: (page: number) => void }) {
  return <section className="overflow-hidden rounded-3xl bg-white shadow-[4px_4px_0_rgba(187,202,196,0.2),inset_2px_2px_4px_rgba(215,219,218,0.5)]">
    <div className="overflow-x-auto"><table className="w-full min-w-[var(--admin-table-min-width)] border-collapse text-left"><thead className="bg-surface-soft text-xs font-bold uppercase tracking-[0.6px] text-muted-strong"><tr><th className="w-10 px-4 py-4"><span className="sr-only">Selecionar</span></th><th className="px-4 py-4">Detalhes do local</th><th className="px-4 py-4">Tipo</th><th className="px-4 py-4">Região</th><th className="px-4 py-4">Contatos</th><th className="px-4 py-4">Status</th><th className="w-20 px-4 py-4 text-right">Ações</th></tr></thead><tbody>
      {resources.length === 0 ? <tr><td className="px-4 py-12 text-center text-sm text-muted" colSpan={7}>Nenhum apoio encontrado.</td></tr> : resources.map((resource) => { const Icon = categoryIcons[resource.category]; return <tr className="border-t border-[#bbcac4]/15" key={resource.id}><td className="px-4 py-4"><span className="block h-5 w-5 rounded-full border border-[#bbcac4]/60" aria-hidden="true" /></td><td className="max-w-[var(--admin-table-title-max)] px-4 py-4"><p className="truncate text-base text-admin-text">{resource.name}</p><p className="truncate text-xs text-muted">{resource.address}</p></td><td className="px-4 py-4"><span className={cx('inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-semibold', categoryClassNames[resource.category])}><Icon size={12} />{supportCategoryLabels[resource.category]}</span></td><td className="px-4 py-4 text-sm text-admin-text">{resource.city}<span className="block text-xs text-muted">{resource.state}</span></td><td className="px-4 py-4 text-sm text-muted-strong">{resource.phone}</td><td className="px-4 py-4"><span className={cx('inline-flex rounded-full px-3 py-1 text-xs font-semibold', resource.status === 'ATIVO' ? 'bg-brand-mint/20 text-brand-teal' : 'bg-[#e6e9e8] text-muted-strong')}>{supportStatusLabels[resource.status]}</span></td><td className="px-4 py-4 text-right"><Link aria-label={`Editar ${resource.name}`} className="inline-grid h-8 w-8 place-items-center rounded-full text-muted-strong transition hover:bg-surface-soft focus-visible:outline-2 focus-visible:outline-brand-mint" to={`/radar-de-apoio/${resource.id}/editar`}><Pencil className="hidden" size={16} /><MoreVertical size={18} /></Link></td></tr> })}
    </tbody></table></div>
    <footer className="flex items-center justify-between border-t border-[#bbcac4]/15 bg-surface-soft px-4 py-3"><p className="text-xs text-muted">Mostrando {resources.length === 0 ? 0 : page} de {totalPages}</p><div className="flex items-center gap-2"><button aria-label="Página anterior" className="rounded px-2 text-muted-strong disabled:opacity-40" disabled={page <= 1} onClick={() => onPageChange(page - 1)} type="button">‹</button>{Array.from({ length: totalPages }, (_, index) => index + 1).map((item) => <button aria-current={page === item ? 'page' : undefined} className={cx('grid h-7 w-7 place-items-center rounded-full text-xs', page === item ? 'bg-brand-teal text-white' : 'text-admin-text hover:bg-white')} key={item} onClick={() => onPageChange(item)} type="button">{item}</button>)}<button aria-label="Próxima página" className="rounded px-2 text-muted-strong disabled:opacity-40" disabled={page >= totalPages} onClick={() => onPageChange(page + 1)} type="button">›</button></div></footer>
  </section>
}
